apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: myapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: my-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: mynginx
          image: nginx



#To create and excute replicaset.yaml file (rs=replicaset)
# kubectl create -f replicaset.yaml  : To create replicaset
# kubectl get replicaset  : To List all replicaset
# kubectl get pods    : To list podes in the cluster
# kubectl decribe rs/my-replicaset   : To show all info about replicaset
# kubectl delete pod <my-replicaset-29M52>  : To delete pod
# Deleted pod will create again due to replicaset you can increase and decrease replicaset in code
# kubectl apply -f replicaset.yaml  : To update configure is added
# kubectl delete rs my-replicaset   : To delete replicasets and pods. pods will not create again
