apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-cip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-cip
  template:
    metadata:
      labels:
        app: my-app-cip
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-cip
  labels:
    app: my-app-cip
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app-cip



# --- Is used to divide the programs in the same file. 
# we can not see the external ip in clusterip service.
# We can access pods within the cluster. 
# kubectl create -f clusterip-service-.yaml 
# kubectl get pods
# kubectl get pods -o wide
# kubectl get service (svc)
# kubectl describe svc my-app-cip :- To know service mapped to the pods.
# kubectl get nodes -o wide :- to show the nodes in the cluster.

