apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-np
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-np
  template:
    metadata:
      labels:
        app: my-app-np
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-np
  labels:
    app: my-app-np
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app-np


# nodeport service is used for testing purpose.
# kubectl apply -f nodeport-service.yaml
# kubectl get deploy
# kubectl get pods
# kubectl get svc
# kubectl get nodes -o wide 
# <Externalip address>:<nodeport no> :- search in browser will acesses externally.
# In nodeport service port no is always grater that 30,000. 
# kubectl describe svc my-app-np
